FROM node:19 as build-stage
WORKDIR /app
COPY package.json .

RUN yarn
COPY ./ .
RUN yarn build

FROM node:19 as prod-stage
WORKDIR /app
COPY --from=build-stage /app/.output ./.output
CMD [ "node", ".output/server/index.mjs" ]
