[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "20"

[build]
  publish = "dist"
  command = "npx yarn && npx yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
